# Em: dailyquest-auth/docker-compose.yml

services:
  # Serviço de Autenticação
  auth:
    build: .
    container_name: dailyquest-auth-api # Nome claro
    ports:
      - "8080:8080" # Porta diferente para não dar conflito (usei 8001)
    volumes:
      - ./src:/app/src
    env_file: .env # Carrega o .env (com DATABASE_URL e SECRET_KEY)
    networks:
      - dailyquest-net # Conecta na rede externa

networks:
  # Diz ao Docker para usar a rede criada pelo outro compose
  dailyquest-net:
    external: true