services:
  auth:
    build: .
    container_name: dailyquest-auth-api 
    ports:
      - "8080:8080" 
    volumes:
      - ./src:/app/src
    env_file: .env 
    networks:
      - dailyquest-net 

networks:
  dailyquest-net:
    external: true